workspaceLocation: go-helpers/go-helpers.code-workspace
tasks:
  - init: |
      go install gotest.tools/gotestsum@latest
      cd httpo && go get && cd -
      cd logo && go get && cd -
      exit

vscode:
  extensions:
    - golang.go
